# Generated by Django 4.1.1 on 2022-10-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="himage",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
