# Generated by Django 4.1.2 on 2022-10-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.SmallIntegerField(null=True, verbose_name="리뷰 점수"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hinfo",
            field=models.TextField(null=True, verbose_name="숙소 안내"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hmap",
            field=models.TextField(null=True, verbose_name="숙소 지도"),
        ),
    ]
