# Generated by Django 4.1.2 on 2022-10-24 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_comment_score_hotel_hinfo_hotel_hmap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="voter",
            field=models.ManyToManyField(
                null=True, related_name="voter_hotel", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
