# Generated by Django 4.1.2 on 2022-10-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_hotel_voter"),
    ]

    operations = [
        migrations.RemoveField(model_name="hotel", name="hcontent",),
    ]
