# Generated by Django 4.1.2 on 2022-10-25 01:45

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_hotel_himage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='himage',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='voter',
            field=models.ManyToManyField(related_name='voter_hotel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.image_upload_to)),
                ('order', models.SmallIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('hotel', 'order'), name='unique_together'),
        ),
    ]
