# Generated by Django 4.1.2 on 2022-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_hotel_himage_alter_hotel_voter_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
