# Generated by Django 4.1.2 on 2022-10-25 02:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.AddField(
            model_name='room',
            name='rimage',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to),
        ),
    ]
