# Generated by Django 4.1.2 on 2022-10-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_hotel_himage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='himage',
        ),
    ]
