# Generated by Django 4.1.2 on 2022-10-25 02:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_room_rimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='himage',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to),
        ),
    ]
