# Generated by Django 4.1.2 on 2022-10-25 02:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hotel_himage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rimage',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_to),
        ),
    ]
