# Generated by Django 4.1.2 on 2022-10-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_room_rimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="leave_at",
            field=models.DateField(verbose_name="퇴실날짜"),
        ),
        migrations.AlterField(
            model_name="order",
            name="visit_at",
            field=models.DateField(verbose_name="입실날짜"),
        ),
    ]
