# Generated by Django 4.1.2 on 2022-10-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_room_rimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.BooleanField(default=False, verbose_name='가족객실')),
                ('wifi', models.BooleanField(default=False, verbose_name='전구역 WIFI')),
                ('parking', models.BooleanField(default=False, verbose_name='무료주차')),
                ('fitness', models.BooleanField(default=False, verbose_name='피트니스 센터')),
                ('nosmoking', models.BooleanField(default=False, verbose_name='금연 객실')),
                ('breakfast', models.BooleanField(default=False, verbose_name='조식')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel', verbose_name='숙소')),
            ],
        ),
    ]
