# Generated by Django 4.1.2 on 2022-10-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, verbose_name='이름')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('rank', models.SmallIntegerField(choices=[(0, '회원'), (1, '사업자')], verbose_name='회원구분')),
                ('phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='전화번호')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
