# Generated by Django 4.1.2 on 2022-10-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="gender",),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.SmallIntegerField(
                choices=[(0, "member"), (1, "business")], default=0
            ),
            preserve_default=False,
        ),
    ]
