# Generated by Django 4.1.2 on 2022-10-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_gender_user_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
