# Generated by Django 4.1.2 on 2022-10-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="admin", max_length=50, verbose_name="닉네임"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=15, null=True, unique=True, verbose_name="전화번호"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="rank",
            field=models.SmallIntegerField(
                choices=[(0, "회원"), (1, "사업자")], verbose_name="회원구분"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, verbose_name="이름"),
        ),
    ]
