# Generated by Django 4.1.2 on 2022-10-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_nickname_alter_user_phone_alter_user_rank_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={},),
        migrations.RemoveField(model_name="user", name="date_joined",),
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="groups",),
        migrations.RemoveField(model_name="user", name="is_active",),
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.RemoveField(model_name="user", name="is_superuser",),
        migrations.RemoveField(model_name="user", name="last_name",),
        migrations.RemoveField(model_name="user", name="user_permissions",),
    ]
